version: "3.9"

services:
  autopdfparse-backend:
    image: ghcr.io/chidirnweke/autopdfparse-backend:latest
    container_name: autopdfparse_backend
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/health",
          "||",
          "exit",
          "1",
        ]
      interval: 600s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - reverse-proxy
      - telemetry-network

networks:
  reverse-proxy:
    external: true
  telemetry-network:
    external: true
