[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autopdfparse[anthropic,gemini,openai]>=0.1.1",
    "fastapi[standard]>=0.115.12",
    "python-multipart>=0.0.20",
]
